# Generated by Django 2.0.3 on 2018-03-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificadoresExternos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='IdentificadorExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='algunos organismo ponen un código una vez y despues lo cambian', max_length=90, null=True)),
                ('web_definicion_identificadores', models.URLField(blank=True, null=True)),
                ('observaciones_publicas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=190)),
                ('es_organismo_oficial', models.NullBooleanField(default=None)),
                ('web_oficial_organismo', models.URLField(blank=True, null=True)),
                ('ambito_de_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipios.Lugar')),
            ],
        ),
        migrations.AddField(
            model_name='identificadorexterno',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organismos.OrganismoExterno'),
        ),
        migrations.AddField(
            model_name='identificadoresexternos',
            name='identificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organismos.IdentificadorExterno'),
        ),
        migrations.AddField(
            model_name='identificadoresexternos',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Lugar'),
        ),
    ]
