# Generated by Django 2.0.3 on 2018-03-24 01:01

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0002_auto_20180324_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoCrudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=190)),
                ('archivo', models.FileField(blank=True, upload_to='datos/')),
                ('url_sitio_descarga', models.TextField(blank=True, null=True)),
                ('url_archivo', models.TextField(blank=True, null=True)),
                ('observaciones_link', models.TextField(blank=True, help_text='Observaciones sobre la descarga y el sitio original', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ambitos_incluidos', models.ManyToManyField(help_text='Lugares vinculados al dato en cuestion', to='municipios.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenDatoCrudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes-datos/')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones de la imagen', null=True)),
                ('dato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos_crudos.DatoCrudo')),
            ],
        ),
        migrations.CreateModel(
            name='Tagulous_DatoCrudo_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_datocrudo_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='datocrudo',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='datos_crudos.Tagulous_DatoCrudo_tags'),
        ),
    ]
