# Generated by Django 2.0.3 on 2018-03-23 23:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre oficial', max_length=190)),
                ('nombre_resumido', models.CharField(help_text='Nombre corto, informal y más amigable del lugar', max_length=90)),
                ('latlong', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Punto representativo del lugar en el mapa', null=True, srid=4326)),
                ('poligono', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Polígono del lugar en el mapa', null=True, srid=4326)),
                ('pertenece_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipios.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=190)),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.TipoLugar'),
        ),
    ]
