# Generated by Django 2.0.3 on 2018-03-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_crudos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datocrudo',
            options={'verbose_name': 'Dato crudo', 'verbose_name_plural': 'Datos crudos'},
        ),
        migrations.AlterModelOptions(
            name='screendatocrudo',
            options={'verbose_name': 'ScreeShot de dato crudo', 'verbose_name_plural': 'ScreeShots de dato crudo'},
        ),
    ]
