# Generated by Django 2.0.3 on 2018-03-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0002_auto_20180324_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='tipolugar',
            options={'verbose_name': 'Tipo de Lugar', 'verbose_name_plural': 'Tipos de Lugares'},
        ),
    ]
